name: CI
on:
  schedule:
    - cron: |
        0 */12 * * *

jobs:
    linux:
      name: "Linux Py${{ matrix.PYTHON_VERSION }} - ${{ matrix.UPSTREAM_DEV }}"
      runs-on: ubuntu-latest
      env:
        CI: True
        PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      strategy:
        fail-fast: false
        matrix:
          PYTHON_VERSION: ['3.6']
          PYARROW_VERSION: ['latest']
          PANDAS_VERSION: ['latest']
          UPSTREAM_DEV: ['default']
          include:
            - UPSTREAM_DEV: 'nightlies'
              PYARROW_VERSION: 'latest'
              PYTHON_VERSION: '3.8'
      steps:
        - name: Checkout branch
          uses: actions/checkout@v1.2.0
        - name: Run CI
          shell: bash -l {0}
          run: ./ci/circle_build_linux.sh ${{ matrix.PYTHON_VERSION }} ${{ matrix.PYARROW_VERSION }} ${{ matrix.PANDAS_VERSION }} ${{ matrix.UPSTREAM_DEV }}
        - uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
